namespace: finallycoffee
name: services
version: "0.2.2"
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Various ansible roles useful for automating infrastructure
dependencies:
  "community.general": "^11.0.0"
  "community.crypto": "^3.0.3"
  "community.docker": "^4.7.0"
  "containers.podman": "^1.16.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/services
issues: https://codeberg.org/finallycoffee/ansible-collection-services/issues
tags:
  - authelia
  - gitea
  - hedgedoc
  - jellyfin
  - vaultwarden
  - snipeit
  - docker
  - phpldapadmin
  - pretix
  - keycloak
