namespace: finallycoffee
name: services
version: 0.1.6
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Various ansible roles useful for automating infrastructure
dependencies:
  "community.crypto": "^2.0.0"
  "community.docker": "^3.0.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/services
issues: https://codeberg.org/finallycoffee/ansible-collection-services/issues
tags:
  - authelia
  - gitea
  - hedgedoc
  - jellyfin
  - vaultwarden
  - snipe-it
  - docker
