---
gitea_version: "1.24.2"
gitea_user: git
gitea_run_user: "{{ gitea_user }}"
gitea_base_path: "/opt/gitea"
gitea_data_path: "{{ gitea_base_path }}/data"

# Set this to the (sub)domain gitea will run at
gitea_domain: ~

# container config
gitea_container_name: "{{ gitea_user }}"
gitea_container_image_server: "docker.io"
gitea_container_image_name: "gitea"
gitea_container_image_namespace: gitea
gitea_container_image_fq_name: >-
  {{
    [
      gitea_container_image_server,
      gitea_container_image_namespace,
      gitea_container_image_name
    ] | join('/')
  }}
gitea_container_image_tag: "{{ gitea_version }}"
gitea_container_image: >-2
  {{ gitea_container_image_fq_name }}:{{ gitea_container_image_tag }}
gitea_container_networks: []
gitea_container_purge_networks: ~
gitea_container_restart_policy: "unless-stopped"
gitea_container_extra_env: {}
gitea_container_extra_labels: {}
gitea_container_extra_ports: []
gitea_container_extra_volumes: []
gitea_container_state: started
gitea_container_user: ~

# container defaults
gitea_container_base_volumes:
  - "{{ gitea_data_path }}:/data:z"
  - "/home/{{ gitea_user }}/.ssh/:/data/git/.ssh:z"

gitea_container_base_ports:
  - "127.0.0.1:{{ git_container_port_webui }}:{{ git_container_port_webui }}"
  - "127.0.0.1:{{ git_container_port_ssh }}:{{ git_container_port_ssh }}"

gitea_container_base_env:
  USER_UID: "{{ gitea_user_res.uid | default(gitea_user) }}"
  USER_GID: "{{ gitea_user_res.group | default(gitea_user) }}"

gitea_container_base_labels:
  version: "{{ gitea_version }}"

gitea_config_mailer_enabled: false
gitea_config_mailer_type: ~
gitea_config_mailer_from_addr: ~
gitea_config_mailer_smtp_addr: ~
gitea_config_mailer_user: ~
gitea_config_mailer_passwd: ~
gitea_config_mailer_protocol: ~
gitea_config_mailer_sendmail_path: ~
gitea_config_metrics_enabled: false

gitea_config: "{{ gitea_config_base | combine(gitea_extra_config, recursive=True, list_merge='append') }}"
gitea_extra_config: {}
