---
- name: Ensure container mounts are present
  when: authelia_state == 'present'
  block:
    - name: Ensure sqlite database file exists before mounting it
      ansible.builtin.file:
        path: "{{ authelia_sqlite_storage_file }}"
        state: touch
        owner: "{{ authelia_run_user }}"
        group: "{{ authelia_run_group }}"
        mode: "0640"
        access_time: preserve
        modification_time: preserve
      when: authelia_config_storage_local_path | default(false, true)

    - name: Ensure user database exists before mounting it
      ansible.builtin.file:
        path: "{{ authelia_user_storage_file }}"
        state: touch
        owner: "{{ authelia_run_user }}"
        group: "{{ authelia_run_group }}"
        mode: "0640"
        access_time: preserve
        modification_time: preserve
      when: authelia_config_authentication_backend_file_path | default(false, true)

    - name: Ensure notification reports file exists before mounting it
      ansible.builtin.file:
        path: "{{ authelia_notification_storage_file }}"
        state: touch
        owner: "{{ authelia_run_user }}"
        group: "{{ authelia_run_group }}"
        mode: "0640"
        access_time: preserve
        modification_time: preserve
      when: authelia_config_notifier_filesystem_filename | default(false, true)

- name: Ensure authelia container image is {{ authelia_state }}
  community.docker.docker_image:
    name: "{{ authelia_container_image_ref }}"
    state: "{{ authelia_state }}"
    source: pull
    force_source: "{{ authelia_container_image_force_pull }}"
  register: authelia_container_image_info

- name: Ensure authelia container is {{ authelia_container_state }}
  community.docker.docker_container:
    name: "{{ authelia_container_name }}"
    image: "{{ authelia_container_image_ref }}"
    env: "{{ authelia_container_env }}"
    user: "{{ authelia_run_user }}:{{ authelia_run_group }}"
    ports: "{{ authelia_container_ports | default(omit, true) }}"
    labels: "{{ authelia_container_labels }}"
    volumes: "{{ authelia_container_volumes }}"
    networks: "{{ authelia_container_networks | default(omit, true) }}"
    etc_hosts: "{{ authelia_container_etc_hosts | default(omit, true) }}"
    purge_networks: "{{ authelia_container_purge_networks | default(omit, true)}}"
    restart_policy: "{{ authelia_container_restart_policy }}"
    recreate: "{{ authelia_container_recreate | default(omit, true) }}"
    state: "{{ authelia_container_state }}"
  register: authelia_container_info
