---

- name: Restart authelia container
  docker_container:
    name: "{{ authelia_container_name }}"
    state: started
    restart: true
    comparisons:
      '*': ignore
  listen: restart-authelia
